### ISSUE TITLE
Example for RNAmotifs

### ISSUE THREAD

**Issue by xflicsu** [matteocereda/RNAmotifs#1]
Hello Dr,
I try to run RNAmotifs with example data NOVA.txt in "examples" directory.
But at last, I can not result like description as follows:  
######
Selecting significantly enriched motifs...
[1] "NO significant tetrames"
######

My question is whether the NOVA.txt file did not contain enriched motifs or not?

**Comment by Indigofera** [comment]
I have the same issue. I worked "Nova.txt" in "examples" directory. I got the same results: "NO significant tetramers". I checked the counting results.  There are just some hit regions, mostly zeros. 
 Could you please check?

**Comment by matteocereda** [comment]
@xflicsu @Indigofera Hi guys, sorry for the delay. Just to let you know we are currently looking at your issue and we will be back to you asap during these days.
Thanks

**Comment by meettel** [comment]
Hi,
the problem was about the reference genome. There was a mistake in the README, where the reference genome was Human instead of Mouse. Now everything should work fine.
Watch out that in the manuscript we evaluated only degenerate tetramers containing R and Y.
Cheers,

Marco

**Comment by Indigofera** [comment]
Thanks for your reply. 
I could not find this file "R/RNAmaps.R". Where is the file?

**Comment by Indigofera** [comment]
Sorry, previuos comment. You changed the file. I was looking the old one.

**Comment by meettel** [comment]
Exactly, it's "R/selection_of_tetramers.R" now.

**Comment by Indigofera** [comment]
thanks

**Comment by matteocereda** [comment]
Hi @xflicsu 
we uploaded a .sh that will be available in the next upgrade of RNAmotifs, sorry for the incovenience.
We have now uploaded the original sh, things should work fine now.
Please use the correct genome (mouse for NOVA dataset).

**Comment by xflicsu** [comment]
Thanks! It works now.
